server:
  port: 8000

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://discovery-service:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalTrackerFilter
          args:
            baseMessage: Spring Cloud Gateway Global Tracker Filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/fallback/user
        - id: shop-service
          uri: lb://SHOP-SERVICE
          predicates:
            - Path=/shop-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/shop-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            - name: CircuitBreaker
              args:
                name: shop-service
                fallbackuri: forward:/fallback/shop
        - id: recommend-service
          uri: lb://RECOMMEND-SERVICE
          predicates:
            - Path=/recommend-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/recommend-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            - name: CircuitBreaker
              args:
                name: recommend-service
                fallbackuri: forward:/fallback/recommend
        - id: timetable-service
          uri: lb://TIMETABLE-SERVICE
          predicates:
            - Path=/timetable-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/timetable-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            - name: CircuitBreaker
              args:
                name: timetable-service
                fallbackuri: forward:/fallback/timetable
        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservation-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/reservation-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            - name: CircuitBreaker
              args:
                name: reservation-service
                fallbackuri: forward:/fallback/reservation
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/review-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            - name: CircuitBreaker
              args:
                name: review-service
                fallbackuri: forward:/fallback/review

management:
  endpoints:
    web:
      exposure:
        include: health, info

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa